name: Staticcheck
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  staticcheck:
    name: Run Staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21 # Specify your Go version
      - name: Install Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run Staticcheck
        run: |
          staticcheck ./...
